### ISSUE TITLE
[PE-D] Help command not recognized after using 'back' in cards.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113-T13-3/tp#118]
![image.png](https://raw.githubusercontent.com/RemusTeo/ped/main/files/5c55baa3-258e-43b7-94ec-ee99617633ab.png)

Steps to replicate:
1. newgame, input playername
2. card
3. help
4. back
5. help [help command not recognized here]
6. help [help recognized here]

Not really sure what is going on here. Maybe the bug started from step 4? And that the back did not register such that there was no help command there? But afterwards when i type it the the second time it registered.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: RemusTeo/ped#4

**Comment by Yuxinn-J** [comment]
Noted the bug! have fixed thank you 😄
