### ISSUE TITLE
[PE-D] Continue command not working

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113-T13-3/tp#120]
`continue` does not work at all  
![image.png](https://raw.githubusercontent.com/leowyy99/ped/main/files/f0d53e75-0d90-4e4c-af82-3873dfb30d6c.png)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: leowyy99/ped#5

**Comment by oneScotch** [comment]
Seems that The file does not exit as shown in the graph you gave. So it ask your name to generate a new one!
