### ISSUE TITLE
[PE-D] Hangman characters

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113-T13-3/tp#123]
Random characters are accepted.

![image.png](https://raw.githubusercontent.com/leowyy99/ped/main/files/d5bb5822-de06-48bc-9587-64caa0d4c824.png)

![image.png](https://raw.githubusercontent.com/leowyy99/ped/main/files/36fd6a94-f95c-4e53-b49d-003f2dc4fb96.png)

The UG mentioned it accept letters only. Was only expecting alphabets.   
![image.png](https://raw.githubusercontent.com/leowyy99/ped/main/files/b0adc6ab-e226-4d45-80ec-ef055e673482.png)

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: leowyy99/ped#6

**Comment by Yuxinn-J** [comment]
Fixed! Thank you! 😃
