### ISSUE TITLE
[PE-D] Uncaught exception when game finished

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113-T13-3/tp#128]
![image.png](https://raw.githubusercontent.com/zh1huang/ped/main/files/3bf9d9cf-3b24-4adf-81d4-260fa84b4e89.png)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: zh1huang/ped#7

**Comment by Yuxinn-J** [comment]
Noted with thanks 😄 have fixed the bug
