### ISSUE TITLE
[PE-D] Correct answers not shown if question is answered wrongly.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113-T13-3/tp#137]
As a child aged 4-9, I cannot learn from my mistakes when I answer the questions in the quiz game wrongly. Furthermore, even if I get 3/4 correct, I cannot advance to the next game. As such, without knowing what I did wrong, I am stuck.

-------------
Labels: `severity.High` `type.FeatureFlaw`
original: daknam2001/ped#6

**Comment by oneScotch** [comment]
Because you may get the same question after trying many times, so we can't give you the answers.

Maybe we can show the answers to all questions after the user finishes the game? @Vincent6896
