### ISSUE TITLE
[PE-D] Selection of game difficulty throws exit message

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113-T13-3/tp#144]
![image.png](https://raw.githubusercontent.com/RemusTeo/ped/main/files/2cd3f8fd-4584-4b34-8c32-bb97c26ca468.png)

Steps to replicate:
1. newgame, input playername
2. start
3. e [input when prompt for gamemode] 
4. Shows exit message?

Seems like no proper input validation done for game mode selection. Maybe default switch case statement will show exit message? (because any other input will also show same)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: RemusTeo/ped#8

**Comment by Yuxinn-J** [comment]
Noted with thanks 😄 have fixed the problem
