### ISSUE TITLE
[PE-D] Restricting user inputs for level 2 game

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113-T13-3/tp#145]
![image.png](https://raw.githubusercontent.com/zh1huang/ped/main/files/22ff38a0-6cfc-4794-9046-2a6eb0491e6e.png)

Should you be allowing only True/False inputs? What if there is a typo?

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: zh1huang/ped#12

**Comment by oneScotch** [comment]
only True/False inputs. Thank you for your advice. Have made it clearer
