### ISSUE TITLE
[PE-D] Program wrongly reports that my save file does not exist when it does exist. It's just invalid

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113-T13-3/tp#147]
![image.png](https://raw.githubusercontent.com/SeanRobertDH/ped/main/files/262275cd-e48e-465f-b187-8712c9ee7684.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: SeanRobertDH/ped#17

**Comment by oneScotch** [comment]
Seems fine from my side. Maybe try again?
Ideally, player ID does not equal player Name.
