### ISSUE TITLE
[PE-D] Storage not implemented

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113-T13-3/tp#153]
Storage does not seem to be implemented properly?

![image.png](https://raw.githubusercontent.com/zh1huang/ped/main/files/79be6dde-739f-45ee-9465-0737a4d6cfbe.png)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: zh1huang/ped#13

**Comment by oneScotch** [comment]
Thank you and done. If possible, please help us test the project again :)
