### ISSUE TITLE
[PE-D] Navigation issue

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113-T13-3/tp#156]
![image.png](https://raw.githubusercontent.com/daknam2001/ped/main/files/3b4591d9-60ff-4317-b455-d8dffff75057.png)

After I typed a wrong command, and then typed a correct command, the correct command is not recognized and I am brought back to the 'start'.

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: daknam2001/ped#11

**Comment by Yuxinn-J** [comment]
Noted with thanks 😄 have fixed the bug
