### ISSUE TITLE
Code Review for @Yuxinn-J

### ISSUE THREAD

**Issue by iamabhishek98** [AY2122S1-CS2113-T13-3/tp#157]
@Yuxinn-J
 
![image](https://user-images.githubusercontent.com/42940729/139572182-2ef94da9-487d-45eb-b1ea-bb638967619b.png)
This function is too big. Break it down into smaller functions. Make it a point not too have too many nested conditions as it makes the code extremely hard to read
There is also a lot of repeated code. Follow the DRY principle and use abstract out the repeated code.

**Comment by Yuxinn-J** [comment]
Noted with thanks! 😄 have broken into smaller methods alr and removed useless repeated code.
