### ISSUE TITLE
DG Review - General

### ISSUE THREAD

**Issue by iamabhishek98** [AY2122S1-CS2113-T13-3/tp#93]
- found a few markdown bugs as shown below:
![image](https://user-images.githubusercontent.com/42940729/139195697-f48e67e4-214f-4973-abf2-b33eb75adcb7.png)
![image](https://user-images.githubusercontent.com/42940729/139195726-5e925435-59f2-462a-acaf-c26cba6253c1.png)
- missing object and sequence diagrams
- very few user stories

**Comment by Yuxinn-J** [comment]
Fixed! Thank you for your advice! 😄
